### ISSUE TITLE
Does it support pytorch 1.0.0 or later verison？

### ISSUE THREAD

**Issue by zengqixun123** [junyanz/VON#18]
Thanks a lot and waiting for your answer!

**Comment by junyanz** [comment]
It should support PyTorch 1.0. But let us know if you find any issues.

**Comment by scamper07** [comment]
Hi,
I'm unable to get it running with PyTorch 1.3
I get the following error

`dataset [ImageAndDFDataset] was created
enable cudnn benchmark
initialization method [kaiming]
loading model from /home/student/Projects/VON/scripts/../final_models/models_3D/car_df_G_3D.pth
initialization method [kaiming]
loading model from /home/student/Projects/VON/scripts/../final_models/models_2D/car_df/latest_net_G_AB.pth
initialization method [kaiming]
loading model from /home/student/Projects/VON/scripts/../final_models/models_2D/car_df/latest_net_E.pth
Traceback (most recent call last):
  File "/home/student/Projects/VON/render_module/render_sketch.py", line 2, in <module>
    from .vtn.vtn.functions import grid_sample3d, affine_grid3d
  File "/home/student/Projects/VON/render_module/vtn/vtn/functions/__init__.py", line 2, in <module>
    from .grid_sample3d import grid_sample3d
  File "/home/student/Projects/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 3, in <module>
    from .._ext import vtn_lib
  File "/home/student/Projects/VON/render_module/vtn/vtn/_ext/vtn_lib/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/student/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
`

Any way to fix this?
I cannot use version 0.4.1 since i have the new Quadro RTX 4000 card and it needs CUDA10 and all newer version packages

**Comment by ztzhang** [comment]
Hi, pytorch has changed its ffi interface and sorry we currently do not have the bandwidth to do a full upgrade.  I'll see if I can find time to do this during the holidays.

**Comment by scamper07** [comment]
Thank you for your reply.
I got it working with PyTorch 0.4.1 CUDA 9.2
