### ISSUE TITLE
No module named 'vtn'

### ISSUE THREAD

**Issue by biexiangduo** [junyanz/VON#24]
hello,
when i ran "bash ./scripts/figures.sh 0 car df"
it occured errors:
 
+ GPU_IDS=0
+ CLASS=car
+ DATASET=df
+++ dirname ./scripts/figures.sh
++ cd ./scripts
++ pwd -P
+ SCRIPTPATH=/home/pf/VON/scripts
+ ROOT_DIR=/home/pf/VON/scripts/..
+ MODEL2D_DIR=/home/pf/VON/scripts/../final_models/models_2D/car_df/latest
+ MODEL3D_DIR=/home/pf/VON/scripts/../final_models/models_3D/car_df
+ RESULTS_DIR=/home/pf/VON/scripts/../results/fig_car_df/
+ NUM_SHAPES=20
+ NUM_SAMPLES=5
+ python test.py --gpu_ids 0 --results_dir /home/pf/VON/scripts/../results/fig_car_df/ --model2D_dir /home/pf/VON/scripts/../final_models/models_2D/car_df/latest --model3D_dir /home/pf/VON/scripts/../final_models/models_3D/car_df --class_3d car --phase val --dataset_mode image_and_df --model test --n_shapes 20 --n_views 5 --reset_texture --reset_shape --suffix car_df
----------------- Options ---------------
                D_norm_3D: none                          
                G_norm_3D: batch3d                       
             aspect_ratio: 1.0                           
               batch_size: 12                            
          checkpoints_dir: ../../results_texture/        
                 class_3d: car                           
             color_jitter: False                         
               crop_align: False                         
                crop_size: 128                           
                 dataroot: None                          
             dataset_mode: image_and_df                  	[default: base]
               df_flipped: False                         
                 df_sigma: 8.0                           
                    df_th: 0.9                           
          display_winsize: 128                           
                    epoch: latest                        
                 gan_mode: lsgan                         
                  gpu_ids: 0                             
               init_param: 0.02                          
                init_type: kaiming                       
                 input_nc: 1                             
             interp_shape: False                         
           interp_texture: False                         
                   ios_th: 0.01                          
                  isTrain: False                         	[default: None]
                load_size: 128                           
         max_dataset_size: inf                           
                    model: test                          	[default: base]
              model2D_dir: /home/pf/VON/scripts/../final_models/models_2D/car_df/latest	[default: None]
              model3D_dir: /home/pf/VON/scripts/../final_models/models_3D/car_df	[default: None]
                 n_shapes: 20                            	[default: 10]
                  n_views: 5                             	[default: 10]
                     name: car_df                        	[default: experiment_name]
                      ndf: 64                            
                   ndf_3d: 64                            
                      nef: 64                            
                     netD: multi                         
                  netD_3D: D0                            
                     netE: adaIN                         
                     netG: resnet_cat                    
                  netG_3D: G0                            
                      ngf: 64                            
                   ngf_3d: 64                            
                       nl: relu                          
                  no_flip: False                         
               no_largest: False                         
                     norm: inst                          
                   num_Ds: 2                             
              num_threads: 6                             
                 nz_shape: 200                           
               nz_texture: 8                             
                output_nc: 3                             
                    phase: val                           
               pose_align: False                         
                pose_type: hack                          
               print_grad: False                         
             random_shift: False                         
              random_view: False                         
               real_shape: False                         
             real_texture: False                         
               render_25d: False                         
                render_3d: False                         
              reset_shape: True                          	[default: False]
            reset_texture: True                          	[default: False]
           resize_or_crop: crop_real_im                  
              results_dir: /home/pf/VON/scripts/../results/fig_car_df/	[default: ../results/]
                     seed: 0                             
           serial_batches: False                         
               show_input: False                         
                   suffix: car_df                        	[default: ]
                   use_df: False                         
              use_dropout: False                         
                  verbose: False                         
                voxel_res: 128                           
                where_add: all                           
----------------- End -------------------
dataset [ImageAndDFDataset] was created
enable cudnn benchmark
initialization method [kaiming]
loading model from /home/pf/VON/scripts/../final_models/models_3D/car_df_G_3D.pth
initialization method [kaiming]
loading model from /home/pf/VON/scripts/../final_models/models_2D/car_df/latest_net_G_AB.pth
initialization method [kaiming]
loading model from /home/pf/VON/scripts/../final_models/models_2D/car_df/latest_net_E.pth
Traceback (most recent call last):
  File "/home/pf/VON/render_module/render_sketch.py", line 2, in <module>
    from .vtn.vtn.functions import grid_sample3d, affine_grid3d
  File "/home/pf/VON/render_module/vtn/vtn/functions/__init__.py", line 2, in <module>
    from .grid_sample3d import grid_sample3d
  File "/home/pf/VON/render_module/vtn/vtn/functions/grid_sample3d.py", line 3, in <module>
    from .._ext import vtn_lib
  File "/home/pf/VON/render_module/vtn/vtn/_ext/vtn_lib/__init__.py", line 3, in <module>
    from ._vtn_lib import lib as _lib, ffi as _ffi
ImportError: /home/pf/VON/render_module/vtn/vtn/_ext/vtn_lib/_vtn_lib.so: undefined symbol: __cudaPopCallConfiguration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = create_model(opt)
  File "/home/pf/VON/models/__init__.py", line 59, in create_model
    instance = model(opt)
  File "/home/pf/VON/models/test_model.py", line 34, in __init__
    self.setup_DR(opt)
  File "/home/pf/VON/models/base_model.py", line 159, in setup_DR
    from render_module.render_sketch import VoxelRenderLayer, CroppingLayer, GetRotationMatrix, FineSizeCroppingLayer
  File "/home/pf/VON/render_module/render_sketch.py", line 4, in <module>
    from vtn.vtn.functions import grid_sample3d, affine_grid3d
ModuleNotFoundError: No module named 'vtn'

------------
i don not install render ,is this the reason?

**Comment by biexiangduo** [comment]
sorry ,i forgot paste my enviroment:
ubuntu 16.04
gtx 1080ti
and i install cuda 9.0 does this collide the virtual conda envrionment of cuda8.0?

**Comment by biexiangduo** [comment]
ubuntu 16 cuda 9.0  1080ti

**Comment by biexiangduo** [comment]
problem solved .the cuda collide .my computer install cuda 9.0 it collide the von project of cuda 8.0
