### ISSUE TITLE
Fail to compile `./install.sh`:  distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by zhibo-liu** [junyanz/VON#3]
I tried to run `./install.sh` 
## here is my conifg:
- GeForce RTX 2080 Ti
- CUDA version 9.2.148
- ubuntu version16.04 LTS
- gcc version: 5.4.0
- conda environemnt python 3.6 with pytorch 0.4.1

## here is the error
```bash
Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o vtn_cuda_kernel_generic.cu.o vtn_cuda_kernel_generic.cu -x cu -Xcompiler -fPIC -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/TH -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC -I /data/zhibo/codebase/VON/render_module/vtn/vtn/src         -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/optional.h:19,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/Error.h:4,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/Allocator.h:6,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/TH/THAllocator.h:6,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:5,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4,
                 from vtn_cuda_kernel_generic.cu:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/data/zhibo/codebase/VON/render_module/vtn
Including CUDA code.
generating /tmp/tmpeiqqa8a6/_vtn_lib.c
setting the current directory to '/tmp/tmpeiqqa8a6'
running build_ext
building '_vtn_lib' extension
creating data
creating data/zhibo
creating data/zhibo/codebase
creating data/zhibo/codebase/VON
creating data/zhibo/codebase/VON/render_module
creating data/zhibo/codebase/VON/render_module/vtn
creating data/zhibo/codebase/VON/render_module/vtn/vtn
creating data/zhibo/codebase/VON/render_module/vtn/vtn/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DWITH_CUDA -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/data/zhibo/codebase/VON/render_module/vtn/vtn/src -I/home/zhibo/anaconda3/envs/von/include/python3.6m -c _vtn_lib.c -o ./_vtn_lib.o -std=c99 -fopenmp
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DWITH_CUDA -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/data/zhibo/codebase/VON/render_module/vtn/vtn/src -I/home/zhibo/anaconda3/envs/von/include/python3.6m -c /data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn.c -o ./data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn.o -std=c99 -fopenmp
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DWITH_CUDA -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/data/zhibo/codebase/VON/render_module/vtn/vtn/src -I/home/zhibo/anaconda3/envs/von/include/python3.6m -c /data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn_cuda_generic.c -o ./data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn_cuda_generic.o -std=c99 -fopenmp
gcc -pthread -shared -L/home/zhibo/anaconda3/envs/von/lib -Wl,-rpath=/home/zhibo/anaconda3/envs/von/lib,--no-as-needed -L/home/zhibo/anaconda3/envs/von/lib -Wl,-rpath=/home/zhibo/anaconda3/envs/von/lib,--no-as-needed ./_vtn_lib.o ./data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn.o ./data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn_cuda_generic.o /data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn_cuda_kernel_generic.cu.o -L/home/zhibo/anaconda3/envs/von/lib -lpython3.6m -o ./_vtn_lib.so
gcc: error: /data/zhibo/codebase/VON/render_module/vtn/vtn/src/vtn_cuda_kernel_generic.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/unixccompiler.py", line 196, in link
    self.spawn(linker + ld_args)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/unixccompiler.py", line 198, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 52, in <module>
    ffi.build()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o calc_prob_kernel.cu.o calc_prob_kernel.cu -x cu -Xcompiler -fPIC -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/TH -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include -I /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC -I /data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src         -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61         -gencode arch=compute_70,code=sm_70
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/optional.h:19,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/Error.h:4,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/ATen/Allocator.h:6,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/TH/THAllocator.h:6,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:5,
                 from /home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4,
                 from calc_prob_kernel.cu:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/data/zhibo/codebase/VON/render_module/calc_prob
generating /tmp/tmpti_xa_36/_calc_prob_lib.c
setting the current directory to '/tmp/tmpti_xa_36'
running build_ext
building '_calc_prob_lib' extension
creating data
creating data/zhibo
creating data/zhibo/codebase
creating data/zhibo/codebase/VON
creating data/zhibo/codebase/VON/render_module
creating data/zhibo/codebase/VON/render_module/calc_prob
creating data/zhibo/codebase/VON/render_module/calc_prob/calc_prob
creating data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DWITH_CUDA=True -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src -I/home/zhibo/anaconda3/envs/von/include/python3.6m -c _calc_prob_lib.c -o ./_calc_prob_lib.o -std=c99
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DWITH_CUDA=True -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src -I/home/zhibo/anaconda3/envs/von/include/python3.6m -c /data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src/calc_prob.c -o ./data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src/calc_prob.o -std=c99
gcc -pthread -shared -L/home/zhibo/anaconda3/envs/von/lib -Wl,-rpath=/home/zhibo/anaconda3/envs/von/lib,--no-as-needed -L/home/zhibo/anaconda3/envs/von/lib -Wl,-rpath=/home/zhibo/anaconda3/envs/von/lib,--no-as-needed ./_calc_prob_lib.o ./data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src/calc_prob.o /data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src/calc_prob_kernel.cu.o -L/home/zhibo/anaconda3/envs/von/lib -lpython3.6m -o ./_calc_prob_lib.so
gcc: error: /data/zhibo/codebase/VON/render_module/calc_prob/calc_prob/src/calc_prob_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/unixccompiler.py", line 196, in link
    self.spawn(linker + ld_args)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/distutils/unixccompiler.py", line 198, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 42, in <module>
    ffi.build()
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zhibo/anaconda3/envs/von/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

```

**Comment by ztzhang** [comment]
Thanks for the detailed report!
It seems like your gcc version is a bit old, and to compile the kernels requires c++0x support. Can you retry by using a newer version of gcc? We tested with 6.3.0. 

Also we haven't tested with RTX2080 yet, please let us know if updating gcc does not work for you.

**Comment by lxj616** [comment]
update gcc to 6 solved c++0x problem for me
[https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91](url)

And I edited `render_module/vtn/build.py` due to my sys.platform is linux2, not linux

**Comment by ztzhang** [comment]
thanks for the comment! Closing this issue now.
