### ISSUE TITLE
Training images

### ISSUE THREAD

**Issue by CroMocha** [junyanz/VON#31]
Running into an error when feeding data into the model

I'm trying to train the model for top view car images, so after I downloaded the training data
-  created my own dataset from Google images, replaced /data/images/car
- updated imgs_car.txt
- updated pose_car.npz with my own viewpoints

However, I got the error below. Are there additional steps I'm missing in creating the training data?

Traceback (most recent call last):
  File "train.py", line 22, in <module>
    for i, data in enumerate(dataset):
  File "/media/marcchoo/Data/marcj/Documents/VON/data/__init__.py", line 84, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/marcchoo/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/marcchoo/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/marcchoo/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/marcchoo/anaconda3/envs/von/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/marcchoo/Data/marcj/Documents/VON/data/concat_dataset.py", line 9, in __getitem__
    return tuple(d[i] for d in self.datasets)
  File "/media/marcchoo/Data/marcj/Documents/VON/data/concat_dataset.py", line 9, in <genexpr>
    return tuple(d[i] for d in self.datasets)
  File "/media/marcchoo/Data/marcj/Documents/VON/data/images_dataset.py", line 95, in __getitem__
    return self.get_item(index)
  File "/media/marcchoo/Data/marcj/Documents/VON/data/images_dataset.py", line 115, in get_item
    mask = im_out[3, :, :]
IndexError: index 3 is out of bounds for dimension 0 with size 3

**Comment by CroMocha** [comment]
Ok, I see the mask in the alpha channel.
Are there other modifications that I will need to make?
