### ISSUE TITLE
running the example script

### ISSUE THREAD

**Issue by iyildirim** [junyanz/VON#4]
I downloaded the model using `bash ./scripts/download_model.sh`.

But then when I try

` bash ./scripts/figures.sh 0 car df`

to generate samples, I get the following output.

```
+ GPU_ID=0
+ CLASS=car
+ DATASET=df
+++ dirname ./scripts/figures.sh
++ cd ./scripts
++ pwd -P
+ SCRIPTPATH=/om/user/ilkery/VON/scripts
+ ROOT_DIR=/om/user/ilkery/VON/scripts/..                                                                                                                                   [72/1761]
+ DISPLAY_ID=1
+ MODEL2D_DIR=/om/user/ilkery/VON/scripts/../final_models/models_2D/car_df/latest
+ MODEL3D_DIR=/om/user/ilkery/VON/scripts/../final_models/models_3D/car_df
+ RESULTS_DIR=/om/user/ilkery/VON/scripts/../results/fig_car_df/
+ NUM_SHAPES=20
+ NUM_SAMPLES=5
+ CUDA_VISIBLE_DEVICES=0
+ python ./test.py --results_dir /om/user/ilkery/VON/scripts/../results/fig_car_df/ --model2D_dir /om/user/ilkery/VON/scripts/../final_models/models_2D/car_df/latest --model3D_dir /
om/user/ilkery/VON/scripts/../final_models/models_3D/car_df --class_3d car --phase val --dataset_mode image_and_df --model test --n_shapes 20 --n_views 5 --reset_texture --reset_sha
pe --suffix car_df --batch_size 1 --use_df
----------------- Options ---------------
                D_norm_3D: none
                G_norm_3D: batch3d
             aspect_ratio: 1.0
               batch_size: 1                                    [default: 12]
          checkpoints_dir: ../../results_texture/
                 class_3d: car
             color_jitter: False
               crop_align: False
                 dataroot: None
             dataset_mode: image_and_df                         [default: base]
               df_flipped: False
                 df_sigma: 8.0
                    df_th: 0.9
          display_winsize: 128
                    epoch: latest
                fine_size: 128
                 gan_mode: lsgan
                  gpu_ids: 0
               init_param: 0.02
                init_type: kaiming
                 input_nc: 1
             interp_shape: False
           interp_texture: False
                  isTrain: False                                [default: None]
                load_size: 128                                                                                                                                              [36/1761]
         max_dataset_size: inf
                    model: test                                 [default: stage]
              model2D_dir: /om/user/ilkery/VON/scripts/../final_models/models_2D/car_df/latest    [default: None]
              model3D_dir: /om/user/ilkery/VON/scripts/../final_models/models_3D/car_df [default: None]
                 n_shapes: 20                                   [default: 10]
                  n_views: 5                                    [default: 10]
                     name: car_df                               [default: experiment_name]
                      ndf: 64
                   ndf_3d: 64
                      nef: 64
                     netD: multi
                  netD_3D: D0
                     netE: adaIN
                     netG: resnet_cat
                  netG_3D: G0
                      ngf: 64
                   ngf_3d: 64
                       nl: relu
                  no_flip: False
               no_largest: False
                     norm: inst
                   num_Ds: 2
              num_threads: 6
                 nz_shape: 200
               nz_texture: 8
                output_nc: 3
                    phase: val
               pose_align: False
                pose_type: hack
               print_grad: False
             random_shift: False
              random_view: False
               real_shape: False
             real_texture: False
               render_25d: False
                render_3d: False
              reset_shape: True                                 [default: False]
            reset_texture: True                                 [default: False]
           resize_or_crop: crop_real_im
              results_dir: /om/user/ilkery/VON/scripts/../results/fig_car_df/   [default: ../results/]
                     seed: 0
           serial_batches: False
               show_input: False
                 show_rec: False
                   suffix: car_df                               [default: ]
                       th: 0.01
                   use_df: True                                 [default: False]
              use_dropout: False
                  verbose: False
                voxel_res: 128
                where_add: all
----------------- End -------------------
dataset [ImageAndDFDataset] was created
enable cudnn benchmark
initialization method [kaiming]
loading model from /om/user/ilkery/VON/scripts/../final_models/models_3D/car_df_G_3D.pth
Traceback (most recent call last):
  File "./test.py", line 19, in <module>
    model = create_model(opt)
  File "/om/user/ilkery/VON/models/__init__.py", line 37, in create_model
    instance.initialize(opt)
  File "/om/user/ilkery/VON/models/test_model.py", line 28, in initialize
    self.netG_3D = self.define_G_3D()
  File "/om/user/ilkery/VON/models/base_model.py", line 68, in define_G_3D
    self.load_network(netG, opt.model3D_dir + '_G_3D.pth')
  File "/om/user/ilkery/VON/models/base_model.py", line 142, in load_network
    net.module.load_state_dict(torch.load(path))
  File "/om/user/ilkery/envs/pytorch_v04/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for _netG0:
        Unexpected key(s) in state_dict: "block_0.1.num_batches_tracked", "block_1.1.num_batches_tracked", "block_2.1.num_batches_tracked", "block_3.1.num_batches_tracked", "block_4.1.num_batches_tracked".
```

**Comment by ztzhang** [comment]
Would you mind sharing your pytorch version? Did it happen within the environment provided?

**Comment by iyildirim** [comment]
it's pytorch 0.4.0. And no, I'm using my own environment. Do you suspect of any particular package that I might be missing?

**Comment by ztzhang** [comment]
The code is for pytorch 0.4.1; with 0.4.0 some default behaviours of the normalization layers are not consistent with 0.4.1. 
We highly recommend using the provided environment.
